/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    users: User;
    'api-keys': ApiKey;
    'cc-data-media': CcDataMedia;
    'cc-data-heroes': CcDataHero;
    'cc-data-page-banners': CcDataPageBanner;
    'cc-data-newsletters': CcDataNewsletter;
    'cc-data-categories': CcDataCategory;
    'hunger-data-programs': HungerDataProgram;
    'hunger-data-partners': HungerDataPartner;
    'hunger-data-media': HungerDataMedia;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  globals: {
    'hunger-pages-home': HungerPagesHome;
    'hunger-pages-about': HungerPagesAbout;
    'hunger-pages-donate': HungerPagesDonate;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: {
    first?: string | null;
    last?: string | null;
    full?: string | null;
  };
  roles?: {
    admin?: boolean | null;
  };
  website_access?: ('U.P. Lions Serve' | 'Childhood Cancer' | 'Hunger')[] | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "api-keys".
 */
export interface ApiKey {
  id: number;
  name: string;
  website_access: ('U.P. Lions Serve' | 'Childhood Cancer' | 'Hunger')[];
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cc-data-media".
 */
export interface CcDataMedia {
  id: number;
  alt?: string | null;
  category?: string | null;
  photo_gallery?: boolean | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cc-data-heroes".
 */
export interface CcDataHero {
  id: number;
  name: string;
  image?: number | CcDataMedia | null;
  summary: string;
  story: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cc-data-page-banners".
 */
export interface CcDataPageBanner {
  id: number;
  name: string;
  url: string;
  banner: number | CcDataMedia;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cc-data-newsletters".
 */
export interface CcDataNewsletter {
  id: number;
  name: string;
  volume: number;
  issue: number;
  date?: string | null;
  newsletter_file: number | CcDataMedia;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cc-data-categories".
 */
export interface CcDataCategory {
  id: number;
  name: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hunger-data-programs".
 */
export interface HungerDataProgram {
  id: number;
  logo_image?: number | HungerDataMedia | null;
  title: string;
  title_id?: string | null;
  home_page_description: string;
  description: {
    root: {
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      type: string;
      version: number;
    };
    [k: string]: unknown;
  };
  cta_button?: {
    text?: string | null;
    url?: string | null;
  };
  gallery_images?:
    | {
        image: number | HungerDataMedia;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  description_html?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hunger-data-media".
 */
export interface HungerDataMedia {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    logo?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hunger-data-partners".
 */
export interface HungerDataPartner {
  id: number;
  logo_image?: number | HungerDataMedia | null;
  name: string;
  link?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'api-keys';
        value: number | ApiKey;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hunger-pages-home".
 */
export interface HungerPagesHome {
  id: number;
  title: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hunger-pages-about".
 */
export interface HungerPagesAbout {
  id: number;
  mission_statement?: {
    root: {
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      type: string;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  mission_cta_button?: {
    text?: string | null;
    url?: string | null;
  };
  vision_statement?: {
    root: {
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      type: string;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  mission_statement_html?: string | null;
  vision_statement_html?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hunger-pages-donate".
 */
export interface HungerPagesDonate {
  id: number;
  donate_statement?: {
    root: {
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      type: string;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  donate_cta_button?: {
    text?: string | null;
    url?: string | null;
  };
  donate_statement_html?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}